// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TacosApp.Web.Data;

#nullable disable

namespace TacosApp.Web.Data.Migrations
{
    [DbContext(typeof(TacosDbContext))]
    partial class TacosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.HasKey("MenuId");

                    b.ToTable("Menus", (string)null);

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Description = "こだわりのスパイスで味付けしたビーフと新鮮野菜のタコス",
                            DisplayOrder = 1,
                            ImageUrl = "/images/beef-taco.jpg",
                            IsAvailable = true,
                            Name = "クラシックビーフタコス",
                            Price = 350m
                        },
                        new
                        {
                            MenuId = 2,
                            Description = "やわらかグリルチキンとアボカドソースのタコス",
                            DisplayOrder = 2,
                            ImageUrl = "/images/chicken-taco.jpg",
                            IsAvailable = true,
                            Name = "チキンタコス",
                            Price = 320m
                        },
                        new
                        {
                            MenuId = 3,
                            Description = "プリプリのエビとマンゴーサルサのタコス",
                            DisplayOrder = 3,
                            ImageUrl = "/images/shrimp-taco.jpg",
                            IsAvailable = true,
                            Name = "シュリンプタコス",
                            Price = 380m
                        },
                        new
                        {
                            MenuId = 4,
                            Description = "彩り豊かな野菜とブラックビーンズのタコス",
                            DisplayOrder = 4,
                            ImageUrl = "/images/veg-taco.jpg",
                            IsAvailable = true,
                            Name = "ベジタコス",
                            Price = 300m
                        },
                        new
                        {
                            MenuId = 5,
                            Description = "とろけるチーズをたっぷり挟んだ香ばしいサイドディッシュ",
                            DisplayOrder = 5,
                            ImageUrl = "/images/quesadilla.jpg",
                            IsAvailable = true,
                            Name = "チーズケサディーヤ",
                            Price = 560m
                        },
                        new
                        {
                            MenuId = 6,
                            Description = "クリスピーなチップスにサルサとチーズを重ねた人気サイド",
                            DisplayOrder = 6,
                            ImageUrl = "/images/nachos.jpg",
                            IsAvailable = true,
                            Name = "メキシカンナチョス",
                            Price = 260m
                        },
                        new
                        {
                            MenuId = 7,
                            Description = "爽やかなライムの酸味が効いた炭酸ドリンク",
                            DisplayOrder = 7,
                            ImageUrl = "/images/lime-soda.jpg",
                            IsAvailable = true,
                            Name = "ライムソーダ",
                            Price = 270m
                        },
                        new
                        {
                            MenuId = 8,
                            Description = "濃厚なマンゴーの甘みとヨーグルトのまろやかさが楽しいドリンク",
                            DisplayOrder = 8,
                            ImageUrl = "/images/mango-lassi.jpg",
                            IsAvailable = true,
                            Name = "マンゴーラッシー",
                            Price = 440m
                        });
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeliveryNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.OrderItemTopping", b =>
                {
                    b.Property<int>("OrderItemToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemToppingId"));

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.Property<int>("ToppingId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.HasKey("OrderItemToppingId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("ToppingId");

                    b.ToTable("OrderItemToppings", (string)null);
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToppingId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10,0)");

                    b.HasKey("ToppingId");

                    b.ToTable("Toppings", (string)null);

                    b.HasData(
                        new
                        {
                            ToppingId = 1,
                            DisplayOrder = 1,
                            IsAvailable = true,
                            Name = "グアカモーレ",
                            Price = 80m
                        },
                        new
                        {
                            ToppingId = 2,
                            DisplayOrder = 2,
                            IsAvailable = true,
                            Name = "追加チーズ",
                            Price = 50m
                        },
                        new
                        {
                            ToppingId = 3,
                            DisplayOrder = 3,
                            IsAvailable = true,
                            Name = "ハラペーニョ",
                            Price = 30m
                        },
                        new
                        {
                            ToppingId = 4,
                            DisplayOrder = 4,
                            IsAvailable = true,
                            Name = "サワークリーム",
                            Price = 50m
                        },
                        new
                        {
                            ToppingId = 5,
                            DisplayOrder = 5,
                            IsAvailable = true,
                            Name = "サルサ",
                            Price = 30m
                        },
                        new
                        {
                            ToppingId = 6,
                            DisplayOrder = 6,
                            IsAvailable = true,
                            Name = "パクチー",
                            Price = 20m
                        });
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.OrderItem", b =>
                {
                    b.HasOne("TacosApp.Web.Models.Domain.Menu", "Menu")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TacosApp.Web.Models.Domain.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.OrderItemTopping", b =>
                {
                    b.HasOne("TacosApp.Web.Models.Domain.OrderItem", "OrderItem")
                        .WithMany("Toppings")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TacosApp.Web.Models.Domain.Topping", "Topping")
                        .WithMany("OrderItemToppings")
                        .HasForeignKey("ToppingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Menu", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.OrderItem", b =>
                {
                    b.Navigation("Toppings");
                });

            modelBuilder.Entity("TacosApp.Web.Models.Domain.Topping", b =>
                {
                    b.Navigation("OrderItemToppings");
                });
#pragma warning restore 612, 618
        }
    }
}
